[package]
name = "dynobox-super"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Super image parsing and chunk-planning crate for DynoBox"

[dependencies]
crc32fast.workspace = true
dynobox-core.workspace = true
dynobox-xml.workspace = true
regex = "1.13.1"
sha2 = "0.11.0"
tracing.workspace = true
zerocopy = { version = "0.8.56", features = ["derive"] }

[dev-dependencies]
dynobox-core = { workspace = true, features = ["testutil"] }
tempfile.workspace = true

[lints]
workspace = true
